FROM node:18.0.0

ARG web=/opt/workspace/aelf-bridge-frontend

# Rebuild the source code only when needed
FROM base AS builder
ARG NEXT_PUBLIC_SENTRY_DNS
ARG NEXT_PUBLIC_ANALYTICS_ID
ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG ENV_NAME
ENV NEXT_PUBLIC_SENTRY_DNS=${NEXT_PUBLIC_SENTRY_DNS}
ENV NEXT_PUBLIC_ANALYTICS_ID=${NEXT_PUBLIC_ANALYTICS_ID}
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
ENV NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
ENV ENV_NAME=${ENV_NAME}

# Production image, copy all the files and run next
FROM base AS runner
ARG NEXT_PUBLIC_SENTRY_DNS
ARG NEXT_PUBLIC_ANALYTICS_ID
ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG ENV_NAME
ENV NEXT_PUBLIC_SENTRY_DNS=${NEXT_PUBLIC_SENTRY_DNS}
ENV NEXT_PUBLIC_ANALYTICS_ID=${NEXT_PUBLIC_ANALYTICS_ID}
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
ENV NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID}
ENV ENV_NAME=${ENV_NAME}
WORKDIR ${web}

COPY . ${web}

RUN yarn \
    && NEXT_PUBLIC_SENTRY_DNS=${NEXT_PUBLIC_SENTRY_DNS} NEXT_PUBLIC_ANALYTICS_ID=${NEXT_PUBLIC_ANALYTICS_ID} NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV} NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID} ENV_NAME=${ENV_NAME} yarn build

ENTRYPOINT yarn start

EXPOSE 3000
