name: Test

on:
  push:
    branches: ['dev', 'master']
  pull_request:
    branches: ['dev', 'master']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn lint